### ISSUE TITLE
Duplicate Netlify deployment

### ISSUE THREAD

**Issue by clementbiron** [openfisca/openfisca.org#102]
Despite the removal of the deploymlent configuration on @Morendil Netlify account we still have duplicate GitHub actions with the identifier `thirsty-khorana-a3da09`. This is not necessary and could cause problems.

![image](https://user-images.githubusercontent.com/364319/205056475-e8d8a02f-7d70-46e5-96f5-60e1e65bf2f8.png)

We checked with @MattiSG  if we could do something with the GitHub repository settings but it doesn't seem to be possible.

@Morendil , would you please contact Netlify support to explain the situation? (I'll take care of it but it seems easier if the message comes from your email address linked to your Netlify account).

You should send them a message via the form available here [](https://www.netlify.com/support/) and the following message (you can obviously change it if you want).

```
Hello,

Despite the removal of the https://github.com/openfisca/openfisca.org/ repository deployment configuration on my Netlify account, there are still GitHub actions triggered (for exemple in this pull request: https://github.com/openfisca/openfisca.org/pull/97). 

This seems to be a bug on your end as we can't find a way to disable these Netlify actions in the repository settings.

Your help would be greatly appreciated, by replying to this message or in the following issue: https://github.com/openfisca/openfisca.org/issues/102

Thank you.
```

**Comment by MattiSG** [comment]
All the duplicate build information disappears when I force push (see https://github.com/openfisca/openfisca.org/pull/97 and #101). I believe this is thus a misleading information not flushed properly by GitHub in this edge case, but that the disconnection made by @Morendil was actually successful 😃

I'll close this issue, please reopen if the problem reappears!
