### ISSUE TITLE
Netlify previews are unusable as they redirect to main domain

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca.org#105]
If I try to access the preview deployment for #103 at URL https://deploy-preview-103--openfisca-org.netlify.app/, I get redirected to openfisca.org immediately, thus making the preview deployment unusable.

**Comment by clementbiron** [comment]
You can browse the preview by adding `/fr`or `/en` at the end of the URL.

For exemple `https://deploy-preview-103--openfisca-org.netlify.app/fr/`

But the preview seems to have a CSS loading problem.

**Comment by MattiSG** [comment]
Yes, I tried that but as you can see the CSS is broken then :-/

**Comment by MattiSG** [comment]
That is not as high priority as delivering #103 however 😉
