### ISSUE TITLE
Internationalise website

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca.org#2]
As a French-speaking user, I am presented with the following text on the homepage:

_title: "Transformer le code législatif en code logiciel"_

## Calculer les droits des citoyens

Calculez toute variable d’un système socio-fiscal à partir d’une situation individuelle.

## Prédire les impôts des entreprises

Modélisez tous types d’entités et évaluez leur éligibilité à des charges et à des allégements.

## Déterminer l’impact de réformes

Comparez la loi telle qu’elle est et telle qu’elle pourrait être.

- - - - -

- Redirect to the browser language if none is set in the URL: `openfisca.org/` redirects to `openfisca.org/fr/` if the browser preferred language is French.
- Serve the website in the language given by the first path element: `openfisca.org/fr/` is in French.

**Comment by MattiSG** [comment]
- Try to use Hugo.
- If that doesn't work, use JS to detect browser language and use Jekyll to generate HTML files.

**Comment by benjello** [comment]
Prédire les impôts des entreprises n'est pas exact exact: 
 - on prédit les cotisations sociales à al charge des salariés et des employeurs
 - certaines exonérations de charge et le CICE
 - et surtout on ne calcule pas l'impôt sur les sociétés qui _est_ l'impôt des entreprises dans l'acceptation générale de ce terme

On préférera: calculer le coût du travail, coût de la création d'un emploi.

En anglais: labor cost. Si vous préférez insistez sur les cotisations et les contributions sociales, c'est social security contributions et payroll taxes.

**Comment by benjello** [comment]
@MattiSG @fpagnoux : ce n'est peut-être pas le meilleur endroit pour faire remonter cela. Dois-je ouvrir un ticket spécifique ?

**Comment by fpagnoux** [comment]
@benjello Oui, une issue sur openfisca.org serait le mieux :)

**Comment by fpagnoux** [comment]
- [ ] Translate all pages in French
- [ ] Add the script to redirect to `/en` or `/fr` according to the language preference of the browser
- [ ]  Adapt the continuous integration, for both `openfisca.org` and `openfisca.org/doc`

**Comment by sandcha** [comment]
> Add the script to redirect to /en or /fr according to the language preference of the browser

Tried with [this script](https://github.com/openfisca/openfisca.org/blob/f07f4d70c079328990dbdbd3da219b3385be1ae2/static/scripts/lang.js) that reads the client browser language. It created a loop on page reload. I suspect it to be in contradiction with Hugo default behaviour as Hugo sets a default global value to `en` for `defaultContentLanguage` (cf. [hugo documentation](https://gohugo.io/content-management/multilingual/?email-address=DefaultContentLanguage#translate-your-content)). 

@fpagnoux Any idea on a solution to solve this ? (nginx ?)
