### ISSUE TITLE
Add New Zealand, Barcelona, Italy and Australia NSW

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca.org#32]

**Comment by MattiSG** [comment]
A bit early yet, let's wait for some implementation work to has taken shape  :)

**Comment by renardpal** [comment]
see project database: 
https://docs.google.com/spreadsheets/d/15I_EyDVG18fDPe4HPXtTS7iTBT2Brn9xUsKu021vR9U/edit#gid=0

**Comment by Br3nda** [comment]
And Australia (NSW).
