### ISSUE TITLE
Make newsletters discoverable

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca.org#39]
Context: 
Today, we have newsletters on `openfisca.org` like https://openfisca.org/en/news/2018-10-08-news/ and other specific information like http://openfisca.org/en/news/2018-10-02-time-to-upgrade-python/.

What is expected: 
To be able to find this information by going on the website.

What exists:
The information can only be discovered by getting the precise url on [@OpenFisca](https://twitter.com/OpenFisca) twitter account.

Update `openfisca.org` to make the information discoverable?

**Comment by maukoquiroga** [comment]
By the way, I found this tool that's more or less what I was looking for at the time : https://hackmd.io

**Comment by Morendil** [comment]
Closing to reflect internal consensus to try other ways (Twitter) of informing the community.
