### ISSUE TITLE
Update Footer EN & FR

### ISSUE THREAD

**Issue by renardpal** [openfisca/openfisca.org#52]
When I am reaching the end of a page on OpenFisca, I want to have consistent informations about service status, privacy, legal mentions, communication kit, a direct access to our social networks & email. Plus I want to be motivated into building a project by a CTA "get started!"

Slack icon = anchor link to section "reach the community" on community page
Github icon = https://github.com/openfisca
Twitter icon = https://twitter.com/openfisca?lang=fr
Mail icon = mailto: contact@openfisca.org

> No CSS change needed so far

![footer](https://user-images.githubusercontent.com/44638568/52278596-ae9e1500-2957-11e9-9f4a-98d6b2838f2a.png)
![footer](https://user-images.githubusercontent.com/44638568/52278640-cb3a4d00-2957-11e9-89d0-0a05793db73d.png)

**Comment by sandcha** [comment]
Included in openfisca/fr.openfisca.org#36
