### ISSUE TITLE
text and English review for the Privacy policy page

### ISSUE THREAD

**Issue by renardpal** [openfisca/openfisca.org#54]
I suggest we have a few more words about Matomo / why we do tracking. It's not totally different from what we already have. 
Are you okay with that?
Would you change something?
Can someone review my English?

[privacy policy_en.pdf](https://github.com/openfisca/openfisca.org/files/2797096/privacy.policy_en.pdf)
[privacy policy_fr.pdf](https://github.com/openfisca/openfisca.org/files/2797097/privacy.policy_fr.pdf)

**Comment by Morendil** [comment]
Opt Out Matomo -> Opt Out of Matomo
It’s also a precious tool -> They are also a precious tool
OpenSource -> Open Source (en français également)
time spend -> time spent
 are being anonymated ->  are anonymized
 totally compliant ->  fully compliant
 check our stats ->  check out our stats (ou see our stats)

**Comment by sandcha** [comment]
Issue resolved 🙂 
Closing.
