### ISSUE TITLE
Add a "community" page

### ISSUE THREAD

**Issue by renardpal** [openfisca/openfisca.org#57]
So that it's easier for future users and visitors to understand the community, I've been created the page. Before implementing it, I'd be happy to know if you have modification suggestions.

![community](https://user-images.githubusercontent.com/44638568/52270858-6f18fe00-2942-11e9-8ae4-e1f5faf9141d.png)
![community](https://user-images.githubusercontent.com/44638568/52270864-7213ee80-2942-11e9-8f6b-adfc4c8fefb9.png)

**Comment by Morendil** [comment]
As for 2019 -> As of 2019
"used by 8 countries" : list has 7 items :)
have been joining -> have joined (ou "have been involved in" ou "have been part of")
each others -> each other
advices -> advice (c'est un substantif [non dénombrable](https://angleterre.org.uk/anglais/denombrables.htm))
Get start -> Get started

**Comment by renardpal** [comment]
Included in openfisca/fr.openfisca.org#36
