### ISSUE TITLE
Update openfisca.org to last and translated fr.openfisca.org

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca.org#68]
Connected to #60 

A new [fr.openfisca.org](https://fr.openfisca.org) is born. 
It contains international examples and the new openfisca identity.

Update [openfisca.org](https://openfisca.org/en/) with:

- [ ]  [fr.openfisca.org](https://github.com/openfisca/fr.openfisca.org) source code
- [ ]  [fr.openfisca.org](https://fr.openfisca.org) content translation in english

> openfisca/fr.openfisca.org#33 needs to be resolved first

**Comment by MattiSG** [comment]
This has been superseded by #103.
