### ISSUE TITLE
Add a banner for Sharing & Reuse Awards 

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca.org#75]
As OpenFisca ended up first in the category of "Most innovative Open Source Software", I think I'd be nice to add it somewhere.

https://ec.europa.eu/isa2/news/winners-sharing-reuse-awards-2019-made-public_en

**Comment by sandcha** [comment]
🙌 It would be great to add this information on the website.
I'm not sure about the banner though. 🤔

**Comment by Br3nda** [comment]
also: CONGRATULATIONS!

**Comment by MattiSG** [comment]
Done in #103.
