### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by clausmullie** [openfisca/openfisca.org#82]
Hi there,

I'd like to report a broken link.

The bottom of your '[before you start](https://openfisca.org/doc/index.html)' page includes:
> Feeling a bit lost? You’re not sure OpenFisca can suit your project? Fill this form and we’ll tell you!

with 'fill this form' hyperlinking to https://antoningarrone.typeform.com/to/FGkioe

This link returns the message:
>  This typeform is private—only the person who created it can access it

**Comment by maukoquiroga** [comment]
Hi @clausmullie, thanks for reporting this issue! The link is indeed broken.
