### ISSUE TITLE
Add USA

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca.org#83]
https://twitter.com/newgovrepos/status/1210268161930649603
https://github.com/18F/prototype-openfisca-usa-headstart

cc @alexsoble

**Comment by alexsoble** [comment]
👋 @maukoquiroga Hi there! The repo I created is really just a prototyping / experimentation repo, so I would hold off on adding the USA until it's further along. Thanks!

**Comment by alexsoble** [comment]
Also, this may go without saying, but I'm tinkering with using OpenFisca to model a single federal benefit. Not remotely considering anything country-wide.

**Comment by maukoquiroga** [comment]
Hi @alexsoble! Thanks for the heads up :) Closing for the moment then.
