### ISSUE TITLE
Broken links on available country packages page

### ISSUE THREAD

**Issue by clementbiron** [openfisca/openfisca.org#91]
Hello !

I found some available country packages website down:

- Tunisia Open Fisca website is currently on error 502.

![image](https://user-images.githubusercontent.com/364319/147858093-630d280e-d3ff-445c-8088-cbc8c5fd01a8.png)

- United Kingdom website show an application error.

![image](https://user-images.githubusercontent.com/364319/147858120-9dd365df-588a-45a6-85d3-3a3056932d12.png)

- New South Wales - Australia show an application error.

![image](https://user-images.githubusercontent.com/364319/147858171-1a89e1f6-1cd8-4f5e-b1de-7e4e0a453613.png)

Their all have a CTA on this openfisca.org page: https://openfisca.org/en/countries/

Well, it's not an incredible discovery but I didn't see any issue with it so here it is :)

**Comment by MattiSG** [comment]
After #96 is merged, please update (or remove) URLs referenced here so we can close this issue 🙂

**Comment by MattiSG** [comment]
@clementbiron can you please handle that one? 🙂
