### ISSUE TITLE
Add PolicyEngine to the `Powered by OpenFisca` section

### ISSUE THREAD

**Issue by MaxGhenis** [openfisca/openfisca.org#94]
Would you be open to adding https://policyengine.org to https://openfisca.org/en/#products?

@nikhilwoodruff fyi

**Comment by MattiSG** [comment]
Thanks @MaxGhenis!

Very much so! I'm currently budgeting a full rework of the main website that would include full referencing of all reuses. Right now, the layout makes it hard to list more than 2 reuses for each type.

I suggest to wait 2 weeks before investing work in adding PolicyEngine to a probably soon-to-be-replaced website, but if I haven't gotten back to you back then feel free to open a PR to add it, and we'll migrate it later if needed 🙂

**Comment by clementbiron** [comment]
You could add it from now by adding a `.yml` file to the [showcase folder](https://github.com/openfisca/openfisca.org/tree/master/data/showcase) based on the other uses of OpenFisca presented.
