### ISSUE TITLE
Update Netlify base image

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca.org#98]
Netlify builds are currently broken ([example](https://app.netlify.com/sites/thirsty-khorana-a3da09/deploys/636e1c2bd4c13c0009d28f68)) because:

>  The build image for this site uses Ubuntu 14.04 Trusty Tahr, which is no longer supported.

A link suggests to update the base image.

I see that @Morendil is still listed as the owner of the build system, let's hope we can do that upgrade without him!

**Comment by Morendil** [comment]
Available to help if you need me to do something specific, though. Like transfer ownership 😅

**Comment by Morendil** [comment]
I have located the base image settings, at https://app.netlify.com/sites/<mysite>/settings/deploys - check if you have access ?

Otherwise I can easily switch to 20.04 or even the deprecated (but still supported) 16.04. I very much doubt that the site is sensitive to Ubuntu version but I can't be 100% certain.

**Comment by MattiSG** [comment]
> check if you have access ?

<img width="519" alt="image" src="https://user-images.githubusercontent.com/222463/201325280-eed77fd6-3b9a-41a9-adcd-0ff8ceae8543.png">

> Otherwise I can easily switch to 20.04

If it's easy for you to do, it would be lovely to unblock us 🙂 

> Like transfer ownership

Would probably be good for the long term indeed! I am not familiar with Netlify, but it says “Each Netlify site belongs to a team, even if it’s a team of one.”
The ideal solution would be that there is an OpenFisca team with several members, at least @MattiSG and @sandcha for the moment.
If that is not doable, I guess we could transfer it to @openfisca-bot 🙂

**Comment by Morendil** [comment]
Setting changed. I've triggered a `Clear cache and Deploy`. I'll check if the site at least passes a smoke test, i.e. home page loads.

We get one warning:
```
11:55:23 AM: ---------------------------------------------------------------------
WARNING: Your site had a deprecated version of Ruby pinned (2.3.6), which is incompatible with this
build image. This build image only supports 2.4.x and later. We changed it to 2.7.2.

To learn how to set a custom Ruby version, visit the following link:
https://docs.netlify.com/configure-builds/manage-dependencies/#ruby

If you set a custom Ruby version lower than 2.4.x, you will need to select a different build image (Ubuntu Xenial 16.04).
The current build image only supports 2.4.x and later. You can select a different build image at the following link:
https://app.netlify.com/sites/thirsty-khorana-a3da09/settings/deploys#build-image-selection
```

**Comment by Morendil** [comment]
Ack - the build failed. We get a failure fom Hugo. I'll paste the full log here if my alternate pathway to a build, which is to enable 16.04, doesn't work. Trying that now.

**Comment by Morendil** [comment]
Aww - I can't downgrade to 16.04, as it's deprecated. I'm a bit angry now at this decision by the fine people at Netlify - they could at least have warned me that I could either try 16.04 then 20.04 or directly go to 20.04, but not the other way round.

Investigating the Hugo thing…

```
───────
11:55:44 AM:   1. Build command from Netlify app                             
11:55:46 AM: Creating deploy upload records
11:55:44 AM: ────────────────────────────────────────────────────────────────
11:55:44 AM: ​
11:55:44 AM: $ hugo
11:55:44 AM: panic: interface conversion: interface {} is string, not map[string]interface {}
11:55:44 AM: goroutine 1 [running]:
11:55:46 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:55:44 AM: github.com/gohugoio/hugo/vendor/github.com/nicksnyder/go-i18n/i18n/bundle.parseTranslations(0xc420577dad, 0x7, 0xc4201086e0, 0x15f, 0x15f, 0x429314, 0xc420188000, 0xc42056d1e0, 0xc42056d1d0, 0xc42056d1d0)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/vendor/github.com/nicksnyder/go-i18n/i18n/bundle/bundle.go:100 +0x7a6
11:55:44 AM: github.com/gohugoio/hugo/vendor/github.com/nicksnyder/go-i18n/i18n/bundle.(*Bundle).ParseTranslationFileBytes(0xc420571680, 0xc420577dad, 0x7, 0xc4201086e0, 0x15f, 0x15f, 0xc420577dad, 0x2)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/vendor/github.com/nicksnyder/go-i18n/i18n/bundle/bundle.go:75 +0xdb
11:55:44 AM: github.com/gohugoio/hugo/i18n.addTranslationFile(0xc420571680, 0x1019120, 0xc4201c21c0, 0x0, 0x0)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/i18n/translationProvider.go:88 +0x25b
11:55:44 AM: github.com/gohugoio/hugo/i18n.(*TranslationProvider).Update(0xc420521480, 0xc420328480, 0xc42056d480, 0xbef2fd)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/i18n/translationProvider.go:69 +0x3b8
11:55:44 AM: github.com/gohugoio/hugo/deps.(*Deps).LoadResources(0xc420328480, 0xc4203920c0, 0xc4201c0770)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/deps/deps.go:81 +0x43
11:55:44 AM: github.com/gohugoio/hugo/hugolib.applyDepsIfNeeded(0xc420031000, 0xc4203920c0, 0xc4201c0770, 0x1016ba0, 0xc420273680, 0x1005da0, 0x0, 0xc4205214a0, 0x1005d20, 0xc420521480, ...)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:198 +0x388
11:55:44 AM: github.com/gohugoio/hugo/hugolib.newHugoSites(0xc420031000, 0xc4203920c0, 0x0, 0x1016ba0, 0xc420273680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:134 +0x24d
11:55:44 AM: github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc420031000, 0xc4203920c0, 0x0, 0x1016ba0, 0xc420273680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:227 +0xf5
11:55:44 AM: github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/commands/commandeer.go:203 +0x117
11:55:44 AM: sync.(*Once).Do(0xc4200e07e0, 0xc4200cfa98)
11:55:44 AM: 	/usr/local/go/src/sync/once.go:44 +0xbe
11:55:44 AM: github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc4200e0790, 0xc4200e0001, 0x4, 0x10)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/commands/commandeer.go:188 +0x562
11:55:44 AM: github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0xc420388060, 0x1002880, 0xc420419390, 0xc420419630, 0x0, 0x0, 0x0, 0xd7cce0, 0xc42001c101, ...)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/commands/commandeer.go:99 +0x116
11:55:44 AM: github.com/gohugoio/hugo/commands.initializeConfig(0xd70001, 0xc420388060, 0x1002880, 0xc420419390, 0xc420419630, 0xc42020ec08, 0xc42020ebd8, 0x0)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/commands/hugo.go:111 +0x76
11:55:44 AM: github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc420578a00, 0x1529db0, 0x0, 0x0, 0x0, 0x0)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/commands/commands.go:151 +0x97
11:55:44 AM: github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).execute(0xc420578a00, 0xc42001c190, 0x0, 0x0, 0xc420578a00, 0xc42001c190)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:756 +0x468
11:55:44 AM: github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420578a00, 0xc420419390, 0xc4201aa960, 0xc42020eee8)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:846 +0x30a
11:55:44 AM: github.com/gohugoio/hugo/commands.Execute(0xc42001c190, 0x0, 0x0, 0xc42020ef78, 0x403bec, 0xc42002c118, 0x0)
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/commands/hugo.go:77 +0xbe
11:55:44 AM: main.main()
11:55:44 AM: 	/go/src/github.com/gohugoio/hugo/main.go:27 +0x7b

```

**Comment by Morendil** [comment]
Not yet able to figure out this error, I got a clue [here](https://github.com/gohugoio/hugo/issues/401) but I might also be looking in the wrong place. I have to break for lunch and can only come back later today or even tomorrow.

You might be able to make progress by deploying to a new, separate Netlify site without a custom domain - the error seems unlikely to depend on the domain.

**Comment by MattiSG** [comment]
Thanks @morendil for these first steps! Just like with `openfisca-doc` a few months ago, we seem stuck in a loop of outdated systems and dependencies 😞 I guess a mass upgrade of dependencies will be needed. Any help on that is more than welcome.

> You might be able to make progress by deploying to a new, separate Netlify site without a custom domain - the error seems unlikely to depend on the domain.

I am sorry, I don't understand this last statement, the two sentences seem contradictory. From what I understand indeed, the error seems unlikely to depend on the domain.

**Comment by MattiSG** [comment]
> Not yet able to figure out this error

I would really start with upgrading dependencies (Hugo version, Ruby version). It is likely to be way less painful than trying to pinpoint the source.

**Comment by Morendil** [comment]
Sorry for not being clear - I mean that the only thing "special" about "my" Netlify site is that it's associated with the domain openfisca.org. But without being an owner of that site it's easy to deploy the same Github repo to a new Netlify site, and I expect that the error would reproduce there. So not having (yet) transferred ownership shouldn't be a blocker to investigating the issue, should you wish to do so right away.

**Comment by Morendil** [comment]
I've changed the site settings (via environment variable HUGO_VERSION) to use a (much) more recent version of Hugo (v0.103.1 - didn't want to go quite to the latest version, in case of newly introduced bugs), and got a successful build !

**Comment by Morendil** [comment]
(Also, I'm not seeing a custom domain on this site. I've forgotten how things are set up on the DNS front…)

**Comment by Morendil** [comment]
@MattiSG Regarding this last parenthetical remark: it was bugging me, so I looked into it more closely. Possibly you're already aware of that, but I prefer to point out that currently openfisca.org is being served by Github pages (branch `gh-pages`, rather than `master`), *not* by Netlify.

(To check this, visit one of the language specific pages for the Netlify sites (https://thirsty-khorana-a3da09.netlify.app/en/ for instance) and observe that it has "Packages" instead of "Countries", per commit c41270a. Whereas the pages served at openfisca.org still have "Countries".)

In addition, the CircleCI workflows also specify a Hugo version (0.37), which will need to be updated. Also there is something being done by `openfisca-bot` to keep `gh-pages` up to date, but I'm not sure exactly how that is set up.

**Comment by MattiSG** [comment]
Thank you very much @Morendil for your updates and reports!

> openfisca.org is being served by Github pages (branch `gh-pages`, rather than `master`), _not_ by Netlify

Yes, the current deployment procedure is to build the HTML pages in CI on `master` and then commit the result to `gh-pages` and push it, which enables GitHub to serve the static files. Netlify was added (I assume by you 😊) for previews only.

I am personally quite happy with the current deployment setup, as it is purely static and thus more stable, as seen in the current issue :wink: It could also be replicated with any file host, whereas Netlify does some magic that I don't know.

> To check this[…] Whereas the pages served at openfisca.org still have "Countries".

Thank you very much for pointing that out! I investigated, and there is indeed a build issue on top of this issue. See https://github.com/openfisca/openfisca.org/issues/99#issuecomment-1313229669.

Both could share a common root cause in the antique dependencies, or maybe #99 is a consequence of #95. However, I believe it is not worth investigating further before upgrading dependencies. I thus created #100, which would also simplify the deployment process described above.

> got a successful build !

Can you please confirm the following:

1. You updated the base image for all future builds.
2. The current blocking point is #99, which could be fixed by #100.

**Comment by Morendil** [comment]
Yes and yes ;)

**Comment by clementbiron** [comment]
Hello @Morendil, I think it would help me if you could transfer the management of this deployment to Netlify account with the email contact@openfisca.fr (I'm not used to the procedure, I guess the email is enough but let me know if you need more information) 🙏

**Comment by clementbiron** [comment]
I set up a Netlify deployment process with the OpenFisca Bot account but it doesn't work yet.

The `master` branch is deployed on https://openfisca-org.netlify.app with a redirection problem to https://openfisca.org/en/ I haven't yet understood why 👀 

I enabled deploy preview in the settings but it seems not to have any yet. If I believe the [logs](https://app.netlify.com/sites/thirsty-khorana-a3da09/deploys/636e2d267f5e740009114b8e) of the runs of this [PR](https://github.com/openfisca/openfisca.org/pull/97/checks?check_run_id=9433596414) the actions are linked to @Morendil Netlify account. 

I guess it is possible to reconfigure Netlify GitHub App with the OpenFisca Bot and for that I would need to temporarily get the rights to the deposit. @MattiSG would you pelase give me the rights?

**Comment by clementbiron** [comment]
I have given OpenFisca Bot the rights to the Netlify GitHub app which makes branch deployment work.

![image](https://user-images.githubusercontent.com/364319/203771558-0d3663f3-2a43-46a2-a520-440e1482ed2e.png)

The checks, on the other hand, are still knocked out

![image](https://user-images.githubusercontent.com/364319/203771688-917f854e-caff-4a0a-b535-506292843933.png)

**Comment by Morendil** [comment]
> I guess the email is enough

Unfortunately no, per [this documentation](https://answers.netlify.com/t/support-guide-how-to-transfer-a-netlify-site-to-a-new-owner/3866) it requires creating a new team then adding me as a co-owner, and then I can transfer a site…

> with a redirection problem

From memory, when I was playing around with it last week, the redirection is generated into the top-level index.html file by Hugo, based on the `baseURL` and the `defaultContentLanguage` specified in `config.toml`. You need to go to https://openfisca-org.netlify.app/fr/ or https://openfisca-org.netlify.app/en/ to see the localized content.

**Comment by clementbiron** [comment]
> Unfortunately no, per [this documentation](https://answers.netlify.com/t/support-guide-how-to-transfer-a-netlify-site-to-a-new-owner/3866) it requires creating a new team then adding me as a co-owner, and then I can transfer a site…

Ok, could you please give me your Netlify email acount in order to add you as a co-owner of the OpenFisca Netflify account ? (it maybe better via a DM on OpenFisca Slack)

> From memory, when I was playing around with it last week, the redirection is generated into the top-level index.html file by Hugo, based on the baseURL and the defaultContentLanguage specified in config.toml. You need to go to https://openfisca-org.netlify.app/fr/ or https://openfisca-org.netlify.app/en/ to see the localized content.

Thanks for clarify that! The most important thing is that I can access a branch preview environment by localise the content adding `/fr` or `/en` on the URL.

**Comment by Morendil** [comment]
> give me your Netlify email acount in order to add you as a co-owner of the OpenFisca Netflify account ? (it maybe better via a DM on OpenFisca Slack)

Done ;)

**Comment by clementbiron** [comment]
Thanks! Unfortunately I discovered that it is not possible to have several team members with a free Netlify account.
![image](https://user-images.githubusercontent.com/364319/204340034-0f4f6715-73df-40f8-a5f7-55ac4fafef2e.png)

**Comment by clementbiron** [comment]
Despite adding the rights to the repository (thanks @MattiSG) I can't find how to remove the link between the Netlify GitHub app and Laurent's account.

At this point, I think the easiest way would be for @Morendil to delete the deployment configuration of `openfisca.org` and `openfisca-doc` in your Netlify account.

**Comment by clementbiron** [comment]
Hi Laurent,

Thank you for your deletion on your Netlify account! 

Unfortunately we still have duplicate GitHub shares so I will open a dedicated issue and close this one.
